In [2]:
# Importing the required Librarires

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [4]:
df=pd.read_csv("C:/Users/Prakhar/Downloads/upgrad/Telecom_CHurn/final/telecom_churn_data.csv")

In [5]:
df.head()

,mobile_number,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,last_date_of_month_9,arpu_6,...,sachet_3g_9,fb_user_6,fb_user_7,fb_user_8,fb_user_9,aon,aug_vbc_3g,jul_vbc_3g,jun_vbc_3g,sep_vbc_3g
0,7000842753,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,197.385,...,0,1.0,1.0,1.0,NaN,968,30.4,0.0,101.20,3.58
1,7001865778,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,34.047,...,0,NaN,1.0,1.0,NaN,1006,0.0,0.0,0.00,0.00
2,7001625959,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,167.690,...,0,NaN,NaN,NaN,1.0,1103,0.0,0.0,4.17,0.00
3,7001204172,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,221.338,...,0,NaN,NaN,NaN,NaN,2491,0.0,0.0,0.00,0.00
4,7000142493,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,261.636,...,0,0.0,NaN,NaN,NaN,1526,0.0,0.0,0.00,0.00

In [6]:
df.shape

(99999, 226)

## Data Understanding & Cleaning

In [7]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99999 entries, 0 to 99998
Data columns (total 226 columns):
 #    Column                    Dtype
---   ------                    -----
 0    mobile_number             int64
 1    circle_id                 int64
 2    loc_og_t2o_mou            float64
 3    std_og_t2o_mou            float64
 4    loc_ic_t2o_mou            float64
 5    last_date_of_month_6      object
 6    last_date_of_month_7      object
 7    last_date_of_month_8      object
 8    last_date_of_month_9      object
 9    arpu_6                    float64
 10   arpu_7                    float64
 11   arpu_8                    float64
 12   arpu_9                    float64
 13   onnet_mou_6               float64
 14   onnet_mou_7               float64
 15   onnet_mou_8               float64
 16   onnet_mou_9               float64
 17   offnet_mou_6              float64
 18   offnet_mou_7              float64
 19   offnet_mou_8              float64
 20   offnet_mou_9              float64
 21   roam_ic_mou_6             float64
 22   roam_ic_mou_7             float64
 23   roam_ic_mou_8             float64
 24   roam_ic_mou_9             float64
 25   roam_og_mou_6             float64
 26   roam_og_mou_7             float64
 27   roam_og_mou_8             float64
 28   roam_og_mou_9             float64
 29   loc_og_t2t_mou_6          float64
 30   loc_og_t2t_mou_7          float64
 31   loc_og_t2t_mou_8          float64
 32   loc_og_t2t_mou_9          float64
 33   loc_og_t2m_mou_6          float64
 34   loc_og_t2m_mou_7          float64
 35   loc_og_t2m_mou_8          float64
 36   loc_og_t2m_mou_9          float64
 37   loc_og_t2f_mou_6          float64
 38   loc_og_t2f_mou_7          float64
 39   loc_og_t2f_mou_8          float64
 40   loc_og_t2f_mou_9          float64
 41   loc_og_t2c_mou_6          float64
 42   loc_og_t2c_mou_7          float64
 43   loc_og_t2c_mou_8          float64
 44   loc_og_t2c_mou_9          float64
 45   loc_og_mou_6              float64
 46   loc_og_mou_7              float64
 47   loc_og_mou_8              float64
 48   loc_og_mou_9              float64
 49   std_og_t2t_mou_6          float64
 50   std_og_t2t_mou_7          float64
 51   std_og_t2t_mou_8          float64
 52   std_og_t2t_mou_9          float64
 53   std_og_t2m_mou_6          float64
 54   std_og_t2m_mou_7          float64
 55   std_og_t2m_mou_8          float64
 56   std_og_t2m_mou_9          float64
 57   std_og_t2f_mou_6          float64
 58   std_og_t2f_mou_7          float64
 59   std_og_t2f_mou_8          float64
 60   std_og_t2f_mou_9          float64
 61   std_og_t2c_mou_6          float64
 62   std_og_t2c_mou_7          float64
 63   std_og_t2c_mou_8          float64
 64   std_og_t2c_mou_9          float64
 65   std_og_mou_6              float64
 66   std_og_mou_7              float64
 67   std_og_mou_8              float64
 68   std_og_mou_9              float64
 69   isd_og_mou_6              float64
 70   isd_og_mou_7              float64
 71   isd_og_mou_8              float64
 72   isd_og_mou_9              float64
 73   spl_og_mou_6              float64
 74   spl_og_mou_7              float64
 75   spl_og_mou_8              float64
 76   spl_og_mou_9              float64
 77   og_others_6               float64
 78   og_others_7               float64
 79   og_others_8               float64
 80   og_others_9               float64
 81   total_og_mou_6            float64
 82   total_og_mou_7            float64
 83   total_og_mou_8            float64
 84   total_og_mou_9            float64
 85   loc_ic_t2t_mou_6          float64
 86   loc_ic_t2t_mou_7          float64
 87   loc_ic_t2t_mou_8          float64
 88   loc_ic_t2t_mou_9          float64
 89   loc_ic_t2m_mou_6          float64
 90   loc_ic_t2m_mou_7          float64
 91   loc_ic_t2m_mou_8          float64
 92   loc_ic_t2m_mou_9          float64
 93   loc_ic_t2f_mou_6          float64
 94   loc_ic_t2f_mou_7          float64
 95   loc_ic_t2f_mou_8          float64
 96   loc_ic_t2f_mou_9          float64
 97   loc_ic_mou_6              float64
 98   loc_ic_mou_7              float64
 99   loc_ic_mou_8              float64
 100  loc_ic_mou_9              float64
 101  std_ic_t2t_mou_6          float64
 102  std_ic_t2t_mou_7          float64
 103  std_ic_t2t_mou_8          float64
 104  std_ic_t2t_mou_9          float64
 105  std_ic_t2m_mou_6          float64
 106  std_ic_t2m_mou_7          float64
 107  std_ic_t2m_mou_8          float64
 108  std_ic_t2m_mou_9          float64
 109  std_ic_t2f_mou_6          float64
 110  std_ic_t2f_mou_7          float64
 111  std_ic_t2f_mou_8          float64
 112  std_ic_t2f_mou_9          float64
 113  std_ic_t2o_mou_6          float64
 114  std_ic_t2o_mou_7          float64
 115  std_ic_t2o_mou_8          float64
 116  std_ic_t2o_mou_9          float64
 117  std_ic_mou_6              float64
 118  std_ic_mou_7              float64
 119  std_ic_mou_8              float64
 120  std_ic_mou_9              float64
 121  total_ic_mou_6            float64
 122  total_ic_mou_7            float64
 123  total_ic_mou_8            float64
 124  total_ic_mou_9            float64
 125  spl_ic_mou_6              float64
 126  spl_ic_mou_7              float64
 127  spl_ic_mou_8              float64
 128  spl_ic_mou_9              float64
 129  isd_ic_mou_6              float64
 130  isd_ic_mou_7              float64
 131  isd_ic_mou_8              float64
 132  isd_ic_mou_9              float64
 133  ic_others_6               float64
 134  ic_others_7               float64
 135  ic_others_8               float64
 136  ic_others_9               float64
 137  total_rech_num_6          int64
 138  total_rech_num_7          int64
 139  total_rech_num_8          int64
 140  total_rech_num_9          int64
 141  total_rech_amt_6          int64
 142  total_rech_amt_7          int64
 143  total_rech_amt_8          int64
 144  total_rech_amt_9          int64
 145  max_rech_amt_6            int64
 146  max_rech_amt_7            int64
 147  max_rech_amt_8            int64
 148  max_rech_amt_9            int64
 149  date_of_last_rech_6       object
 150  date_of_last_rech_7       object
 151  date_of_last_rech_8       object
 152  date_of_last_rech_9       object
 153  last_day_rch_amt_6        int64
 154  last_day_rch_amt_7        int64
 155  last_day_rch_amt_8        int64
 156  last_day_rch_amt_9        int64
 157  date_of_last_rech_data_6  object
 158  date_of_last_rech_data_7  object
 159  date_of_last_rech_data_8  object
 160  date_of_last_rech_data_9  object
 161  total_rech_data_6         float64
 162  total_rech_data_7         float64
 163  total_rech_data_8         float64
 164  total_rech_data_9         float64
 165  max_rech_data_6           float64
 166  max_rech_data_7           float64
 167  max_rech_data_8           float64
 168  max_rech_data_9           float64
 169  count_rech_2g_6           float64
 170  count_rech_2g_7           float64
 171  count_rech_2g_8           float64
 172  count_rech_2g_9           float64
 173  count_rech_3g_6           float64
 174  count_rech_3g_7           float64
 175  count_rech_3g_8           float64
 176  count_rech_3g_9           float64
 177  av_rech_amt_data_6        float64
 178  av_rech_amt_data_7        float64
 179  av_rech_amt_data_8        float64
 180  av_rech_amt_data_9        float64
 181  vol_2g_mb_6               float64
 182  vol_2g_mb_7               float64
 183  vol_2g_mb_8               float64
 184  vol_2g_mb_9               float64
 185  vol_3g_mb_6               float64
 186  vol_3g_mb_7               float64
 187  vol_3g_mb_8               float64
 188  vol_3g_mb_9               float64
 189  arpu_3g_6                 float64
 190  arpu_3g_7                 float64
 191  arpu_3g_8                 float64
 192  arpu_3g_9                 float64
 193  arpu_2g_6                 float64
 194  arpu_2g_7                 float64
 195  arpu_2g_8                 float64
 196  arpu_2g_9                 float64
 197  night_pck_user_6          float64
 198  night_pck_user_7          float64
 199  night_pck_user_8          float64
 200  night_pck_user_9          float64
 201  monthly_2g_6              int64
 202  monthly_2g_7              int64
 203  monthly_2g_8              int64
 204  monthly_2g_9              int64
 205  sachet_2g_6               int64
 206  sachet_2g_7               int64
 207  sachet_2g_8               int64
 208  sachet_2g_9               int64
 209  monthly_3g_6              int64
 210  monthly_3g_7              int64
 211  monthly_3g_8              int64
 212  monthly_3g_9              int64
 213  sachet_3g_6               int64
 214  sachet_3g_7               int64
 215  sachet_3g_8               int64
 216  sachet_3g_9               int64
 217  fb_user_6                 float64
 218  fb_user_7                 float64
 219  fb_user_8                 float64
 220  fb_user_9                 float64
 221  aon                       int64
 222  aug_vbc_3g                float64
 223  jul_vbc_3g                float64
 224  jun_vbc_3g                float64
 225  sep_vbc_3g                float64
dtypes: float64(179), int64(35), object(12)
memory usage: 172.4+ MB

In [8]:
# Fetching all recharge columns

col_rech=[]
for col in list(df.columns):
    if ('rech' in col):
        col_rech.append(col)

In [9]:
col_rech

['total_rech_num_6',
 'total_rech_num_7',
 'total_rech_num_8',
 'total_rech_num_9',
 'total_rech_amt_6',
 'total_rech_amt_7',
 'total_rech_amt_8',
 'total_rech_amt_9',
 'max_rech_amt_6',
 'max_rech_amt_7',
 'max_rech_amt_8',
 'max_rech_amt_9',
 'date_of_last_rech_6',
 'date_of_last_rech_7',
 'date_of_last_rech_8',
 'date_of_last_rech_9',
 'date_of_last_rech_data_6',
 'date_of_last_rech_data_7',
 'date_of_last_rech_data_8',
 'date_of_last_rech_data_9',
 'total_rech_data_6',
 'total_rech_data_7',
 'total_rech_data_8',
 'total_rech_data_9',
 'max_rech_data_6',
 'max_rech_data_7',
 'max_rech_data_8',
 'max_rech_data_9',
 'count_rech_2g_6',
 'count_rech_2g_7',
 'count_rech_2g_8',
 'count_rech_2g_9',
 'count_rech_3g_6',
 'count_rech_3g_7',
 'count_rech_3g_8',
 'count_rech_3g_9',
 'av_rech_amt_data_6',
 'av_rech_amt_data_7',
 'av_rech_amt_data_8',
 'av_rech_amt_data_9']

In [10]:
for col in list(df.columns):
    if ('arpu' in col):
        col_rech.append(col)

In [11]:
# Fetching all date columns

col_dates=[]
for col in list(df.columns):
    if ('date' in col):
        col_dates.append(col)

In [12]:
# Calculating missing values in columns

missing = round(100*(df.isnull().sum()/len(df)), 2)
missing[missing != 0]

loc_og_t2o_mou           1.02
std_og_t2o_mou           1.02
loc_ic_t2o_mou           1.02
last_date_of_month_7     0.60
last_date_of_month_8     1.10
                        ...
night_pck_user_9        74.08
fb_user_6               74.85
fb_user_7               74.43
fb_user_8               73.66
fb_user_9               74.08
Length: 166, dtype: float64

In [13]:
# Imputing zeroes for all recharge columns

df[col_rech]=df[col_rech].apply(lambda x: x.fillna(0))

In [17]:
# Fetching all categorical columns

col_categorical=['night_pck_user_6','night_pck_user_7','night_pck_user_8','night_pck_user_9','fb_user_6','fb_user_7','fb_user_8','fb_user_9']

In [18]:
df[col_categorical]=df[col_categorical].apply(lambda x: x.fillna(-1))

In [19]:
df['last_date_of_month_7'].fillna('7/31/2014',inplace = True)
df['last_date_of_month_8'].fillna('8/31/2014',inplace = True)
df['last_date_of_month_9'].fillna('9/30/2014',inplace = True)

In [20]:
# Converting Date Series columns to useful information

df[col_dates] = df[col_dates].apply(pd.to_datetime)
df['duration_last_rech_6']= df['last_date_of_month_6']-df['date_of_last_rech_6']
df['duration_last_rech_7']= df['last_date_of_month_7']-df['date_of_last_rech_7']
df['duration_last_rech_8']= df['last_date_of_month_8']-df['date_of_last_rech_8']
df['duration_last_rech_9']= df['last_date_of_month_9']-df['date_of_last_rech_9']

df['duration_last_rech_6']=df['duration_last_rech_6'].astype(str)
df['duration_last_rech_6']=df['duration_last_rech_6'].str.split(" ",n=3,expand=True)[0]
df.loc[(df['duration_last_rech_6']=='NaT'),'duration_last_rech_6']=0
df['duration_last_rech_6']=df['duration_last_rech_6'].astype(int)

df['duration_last_rech_7']=df['duration_last_rech_7'].astype(str)
df['duration_last_rech_7']=df['duration_last_rech_7'].str.split(" ",n=3,expand=True)[0]
df.loc[(df['duration_last_rech_7']=='NaT'),'duration_last_rech_7']=0
df['duration_last_rech_7']=df['duration_last_rech_7'].astype(int)

df['duration_last_rech_8']=df['duration_last_rech_8'].astype(str)
df['duration_last_rech_8']=df['duration_last_rech_8'].str.split(" ",n=3,expand=True)[0]
df.loc[(df['duration_last_rech_8']=='NaT'),'duration_last_rech_8']=0
df['duration_last_rech_8']=df['duration_last_rech_8'].astype(int)

df['duration_last_rech_9']=df['duration_last_rech_9'].astype(str)
df['duration_last_rech_9']=df['duration_last_rech_9'].str.split(" ",n=3,expand=True)[0]
df.loc[(df['duration_last_rech_9']=='NaT'),'duration_last_rech_9']=0
df['duration_last_rech_9']=df['duration_last_rech_9'].astype(int)

df['duration_last_rech_data_6']= df['last_date_of_month_6']-df['date_of_last_rech_data_6']
df['duration_last_rech_data_7']= df['last_date_of_month_7']-df['date_of_last_rech_data_7']
df['duration_last_rech_data_8']= df['last_date_of_month_8']-df['date_of_last_rech_data_8']
df['duration_last_rech_data_9']= df['last_date_of_month_9']-df['date_of_last_rech_data_9']

df['duration_last_rech_data_6']=df['duration_last_rech_data_6'].astype(str)
df['duration_last_rech_data_6']=df['duration_last_rech_data_6'].str.split(" ",n=3,expand=True)[0]
df.loc[(df['duration_last_rech_data_6']=='NaT'),'duration_last_rech_data_6']=0
df['duration_last_rech_data_6']=df['duration_last_rech_data_6'].astype(int)

df['duration_last_rech_data_7']=df['duration_last_rech_data_7'].astype(str)
df['duration_last_rech_data_7']=df['duration_last_rech_data_7'].str.split(" ",n=3,expand=True)[0]
df.loc[(df['duration_last_rech_data_7']=='NaT'),'duration_last_rech_data_7']=0
df['duration_last_rech_data_7']=df['duration_last_rech_data_7'].astype(int)

df['duration_last_rech_data_8']=df['duration_last_rech_data_8'].astype(str)
df['duration_last_rech_data_8']=df['duration_last_rech_data_8'].str.split(" ",n=3,expand=True)[0]
df.loc[(df['duration_last_rech_data_8']=='NaT'),'duration_last_rech_data_8']=0
df['duration_last_rech_data_8']=df['duration_last_rech_data_8'].astype(int)

df['duration_last_rech_data_9']=df['duration_last_rech_data_9'].astype(str)
df['duration_last_rech_data_9']=df['duration_last_rech_data_9'].str.split(" ",n=3,expand=True)[0]
df.loc[(df['duration_last_rech_data_9']=='NaT'),'duration_last_rech_data_9']=0
df['duration_last_rech_data_9']=df['duration_last_rech_data_9'].astype(int)

In [21]:
# dropping date columns

df=df.drop(col_dates, axis=1)
df.shape

(99999, 222)

In [27]:
cols_mou = []
cols_other = []
for col in list(df[missing.loc[(missing[0]!=0),'index']]):
    if 'mou' in col:
        cols_mou.append(col)
    else:
        cols_other.append(col)
len(cols_mou)

IndexingError: Too many indexers

In [25]:
cols_other

[]

In [ ]:
# Mode for all these columns is zero thus imputng with zero

for col in cols_other:
    df[col].fillna(0,inplace = True)

In [23]:
# Mode for all these columns is zero thus imputng with zero

for col in cols_mou:
    df[col].fillna(0,inplace = True)

In [24]:
missing = round(100*(df.isnull().sum()/len(df)), 2)
missing[missing != 0]

loc_og_t2o_mou    1.02
std_og_t2o_mou    1.02
loc_ic_t2o_mou    1.02
onnet_mou_6       3.94
onnet_mou_7       3.86
                  ...
isd_ic_mou_9      7.75
ic_others_6       3.94
ic_others_7       3.86
ic_others_8       5.38
ic_others_9       7.75
Length: 119, dtype: float64